title: Dustin Ivander
email: dustinduck@duck.com
description: >- # this means to ignore newlines until "baseurl:"
  photographer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 2007Dust
github_username:  DustIv

# Build settings
theme: minima
plugins:
  - jekyll-feed
